version: '3.4'
services:
  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
#    image: walkoff_registry:5000/walkoff_app_HelloWorld-v1-0
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
    restart: "no"

